version: '3.3'
services:
  asterisk-test:
    image: asterisk-test:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asterisk-test-2 
    hostname: asterisk-test-2 
    privileged: true
    ports:
    - 4576:4576
    - 5060:5060/udp
    - 10000-10020:10000-10020/udp
    volumes:
    - ./configs:/etc/asterisk